=== AnatolyGeorgievski/R3build/profiles/ant/schema/config.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment":"Схема валидации конфигурационного файла",
  "$id": "schema/config.json",
  "type": "object",
  "required": ["dev", "ctrl", "bus", "pool", "services"],
  "additionalProperties": false,
  "properties": {
    "$schema": { "type": "string", "format": "path" },
    "$defs":   { "type": "object" },

    "dev": {
      "type": "object",
      "required": ["type", "name"],
      "properties": {
        "type":        { "type": "string", "const": "dev" },
        "name":        { "type": "string" },
        "location":    { "type": "string" },
        "description": { "type": "string" }
      },
      "additionalProperties": false
    },

    "ctrl": {
      "type": "object",
      "required": ["type"],
      "properties": {
        "type": { "type": "string", "enum": ["AMLCtrl","BBCtrl","CVCtrl","zynq7007", "Zynq7020"] }
      },
      "additionalProperties": false
    },

    "psu": {
        "description": "Блоки питания APW12 / APW17 порты подключения и настройки",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "type": { "type": "string", "enum": ["i2c_gpio","fpga","i2c"]},
            "name": { "type": "string"},
            "path": { "type": "string", "pattern": "^/dev/[\\w\\d-]+$"  },
            "port": { "type": "array", "items": { "$ref": "#/$defs/PinNumber" }},
            "gpio_ena": {"$ref": "#/$defs/GPIOport"},
            "V_min": {"type": "number"},
            "V_max": {"type": "number"},
            "V_set": {"type": "number"}
          },
          "required": ["type", "name"],
          "additionalProperties": false
        }
    },

    "cnt": {
        "description": "Счетчики оборотов вентиляторов и расходомеры",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "type": { "type": "string", "enum": ["cnt-gpio","fpga"]},
            "name": { "type": "string"},
            "path": { "type": "string", "pattern": "^/dev/[\\w\\d-]+$"  },
            "port": { "type": "array", "items": { "$ref": "#/$defs/PinNumber" }},
            "edge": { "type": "string", "enum": ["rising","falling"]},
            "bias": { "type": "string", "enum": ["pull-up","pull-down"]},
            "units":{ "type": "string"}
          },
          "required": ["type", "name"],
          "additionalProperties": false
        }
    },

    "bus": {
     "description": "Настройка портов UART для подключения хеш-плат",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["type", "name", "path"],
        "properties": {
          "type":     { "type": "string", "enum": ["tty", "fpga"] },
          "name":     { "$ref": "#/$defs/ObjectId" },
          "path":     { "type": "string", "pattern": "^/dev/[\\w\\d-]+$"  },
          "port":     { "type": "string", "format":"uri-query" },
          "irq":      { "type": "integer", "minimum": 1},
          "baudrate": { "$ref": "#/$defs/Baudrate" },
          "gpio_rst": { "$ref": "#/$defs/PinNumber" },
          "gpio_pd":  { "$ref": "#/$defs/PinNumber" }
        },
        "additionalProperties": false
      }
    },

    "rst": { "$ref": "#/$defs/GPIOport" },
    "pd":  { "$ref": "#/$defs/GPIOport" },
    "env": {
      "type": "object",
      "additionalProperties": true
    },
    "profiles": {
      "type": "object",
      "additionalProperties": true
    },

    "fan": {
        "description": "Описание настройки вентиляторов",
        "type": "array",
        "items": {
            "type": "object",
            "required": ["type", "name", "path"],
            "properties": {
                "type":     { "type": "string", "enum": ["pwm"] },
                "name":     { "$ref": "#/$defs/ObjectId" },
                "path":     { "type": "string", "pattern": "^/sys/class/pwm/pwmchip\\d$"  },
                "port":     { "type": "integer" },
                "period":   { "type": "integer", "minimum":2000, "maximum":100000 },
                "duty_cycle":{"type": "integer", "minimum":2000, "maximum":100000 }
            },
            "additionalProperties": true
        }
    },

    "boards": {
        "description": "Описание хеш-плат, Описание содержит топологию платы: число рядов и число чипов в ряд.",
        "type": "array",
        "items": {
            "type": "object",
            "required": ["type", "chip_id"],
            "properties": {
                "$comment": { "type": "string"},
                "type":     { "type": "string", "pattern": "^(S|T|D|E|L|K|Z)\\d{1,2}([ijk+]|xp)?" },
                "name":     { "type": "string" },
                "chip_id":  { "type": "string", "pattern": "\\d{4}" },
                "chips":    { "description": "Число ASIC-чипов на плате", "type": "integer"},
                "cols":     { "type": "integer", "minimum":1 },
                "rows":     { "type": "integer", "minimum":1 },
                "baud":     { "description": "Рекомендуемая частота передачи данных",
                  "$ref": "#/$defs/Baudrate" },
                "voltage_domains": {"type": "integer"}
            },
            "additionalProperties": false
        }
    },

    "pool": {
      "description": "Список пулов с учетными данными",
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/$defs/Pool" }
    },

    "services": {
        "type": "object",
        "required": ["mcp", "log"],
        "properties": {
            "jsonrpc":{ "$ref": "#/$defs/Service" },
            "stratum":{ "$ref": "#/$defs/Service" },
            "log":    { "$ref": "#/$defs/Service" },
            "mqtt":   { "$ref": "#/$defs/Service" },
            "coap":   { "$ref": "#/$defs/Service" },
            "rest":   { "$ref": "#/$defs/Service" },
            "keys":   { "$ref": "#/$defs/Service" },
            "mcp":    { "$ref": "#/$defs/Service" }
        },
        "additionalProperties": false
    }
  },
  
  "$defs": {
    "ObjectId" :{ "type": "string", "pattern": "^[a-z]+\\.\\d$" },
    "Baudrate" :{ "type": "integer", "enum":[115200,1000000,1500000,2500000,3000000,3125000,6250000,12500000], "default":3125000},
    "PinNumber":{ "type": "integer", "minimum": 0, "maximum":999 },
    "Pool": {
      "type": "object",
      "required": ["url", "login", "passwd"],
      "properties": {
        "$comment": { "type": "string"},
        "url":    { "type": "string", "format": "uri" },
        "worker": { "description": "идентификация оборудования или группы, по MAC адресу",
                    "type": "string", "pattern": "^[0-8A-F]{12}$" },
        "login":  { "type": "string", "description": "учетная запись на сервере"},
        "passwd": { "type": "string", "default":"x" },
        "miner":  { "description": "Название оборудования ${hardware}", "type": "string" },
        "addr":   { "description": "Список IPv4 адресов пула",
                    "type": "array", "items":{ "type":"string", "format": "ipv4"} }
      },
      "additionalProperties": false
    },
    "GPIOport": {
        "type":"object",
        "properties": {
          "$comment": { "type": "string"},
          "type": { "type": "string", "enum":["gpio"], "default":"gpio"},
          "name": { "type": "string", "pattern": "^\\w+\\.[\\w\\d]+"},
          "path": { "type": "string", "pattern": "^/dev/gpiochip\\d$"  },
          "port": { "type": "array", "items": {"type":"integer", "minimum": 0, "maximum": 999}}
        },
        "additionalProperties": false
    },
    "Service": {
      "type": "object",
      "properties": {
        "$comment":    { "type": "string" },
        "type":        { "type": "string" },
        "host":        { "type": "string",  "format": "ipv4/uri" },
        "port":        { "type": "integer", "minimum": 1, "maximum": 65535 },
        "proxy":       { "type": "string",  "format": "ipv4"},
        "keepalive":   { "type": "integer", "minimum": 0 },
        "maxAge":      { "type": "integer", "minimum": 0 },
        "contentType": { "type": "string" },
        "accept":      { "type": "array", "items": { "type": "string" } },
        "logLevel":    { "description": "Logging level", "type":"string", 
          "enum":["emergency","alert","critical","error","warning","notice","info","debug"]},
        "domain":      { "description": "Logging domain",
          "type": "array", "items": { "type": "string" } },
        "description": { "type": "string" }
      },
      "additionalProperties": true
    }
  }
}

=== AnatolyGeorgievski/R3build/profiles/ant/config/config.json
{
"$schema":"schema/config.json",
"dev":{"type":"dev", "name":"Antminer E9-pro", 
	"location":"work", "description":"1-2-3"
},
"ctrl":{"type":"Zynq7020"},
"bus":[
    {"type":"fpga", "name":"brd.1", "baudrate":3125000, "gpio_rst":962, "gpio_pd":964, "path":"/dev/i2c-0"},
    {"type":"fpga", "name":"brd.2", "baudrate":3125000, "gpio_rst":961, "gpio_pd":965, "path":"/dev/i2c-1"}
],
"env":{
	"$comment":"датчики окружения и PIC контроллер"
},
"pool":[
	{
	"url": "stratum+tcp://etc.f2pool.com:8008",
	"worker": "52868CC7EEFC",
	"login": "georgelost",
	"passwd": "x"
	},
	{
	"url": "stratum+tcp://ru.etc.k1pool.org:3820",
	"worker": "52868CC7EEFC",
	"login": "KrcxnmYY8pqPrpXEi7HaWtCePGeJdpHrRBt.ANT",
	"passwd": "x"
	},
	{
	"url": "stratum+tcp://eu.etc.k1pool.com:3833",
	"worker": "52868CC7EEFC",
	"login": "KrcxnmYY8pqPrpXEi7HaWtCePGeJdpHrRBt.ANT",
	"passwd": "x"
	}
],
"services":{
  "log": {
    "type": "file",
    "domains": ["stratum"],
    "contentType": "application/json",
    "description": "журнал операций, в локальный файл"
  },
  "mqtt": {
    "type": "mqtt",
    "id": "1234",
    "host": "192.168.1.10",
    "port": 8883,
    "keepalive": 60,
    "path": "/",
    "domains": ["stratum", "hist", "nonce", "psu"],
    "contentType": "application/json",
    "description": "сервер MQTT"
  },
  "coap": {
    "type": "coap",
    "port": 5683,
    "keepalive": 60,
    "maxAge": 60,
    "contentType": "application/cbor",
    "accept": ["application/json", "application/cbor"],
    "proxy": "192.168.191.199",
    "description": "сервис CoAP локальный, настройка"
  },
  "rest": {
    "type": "http",
    "port": 8080,
    "keepalive": 60,
    "maxAge": 60,
    "contentType": "application/json",
    "accept": ["application/json"],
    "description": "сервис HTTP REST локальный, настройка"
  },
  "keys": {
    "type": "crisp",
    "host": "192.168.191.199",
    "port": 5683,
    "keepalive": 60,
    "description": "сервер CRISP ключей шифрования"
  },
  "mcp": {
    "type": "mcp",
    "port": 8081,
    "path": "/mcp",
    "protocolVersion": "2026-07-28",
    "contentType": "application/json",
    "description": "MCP json-rpc service"
  }
},
"$defs":{}
}
